In [1]:
import numpy as np

In [3]:
#Multiplication in list
a = [1,2,3]
b = [2,3,4]

a*b

TypeError: can't multiply sequence by non-int of type 'list'

In [4]:
#Multiplication in Numpy array
a = np.array([1,2,3])
b = np.array([2,3,4])

a*b

array([ 2,  6, 12])

In [5]:
#2D Array
c = np.array([[2.1,3.1],[4.2,7.2],[5.1,6.1]])

In [6]:
print(c)

[[2.1 3.1]
 [4.2 7.2]
 [5.1 6.1]]


In [7]:
#Get dimension
c.ndim

2

In [8]:
#Get shape
c.shape

(3, 2)

In [9]:
#Get type
c.dtype

dtype('float64')

In [10]:
d = np.array([[1,2],[2,3]])

In [11]:
d.itemsize

4

In [7]:
#Get size
c.itemsize

8

In [8]:
#Get total size
c.nbytes

32

In [16]:
#Set data size
d = np.array([2,3,4], dtype= "int64")

In [17]:
print(d.itemsize)
print(d.nbytes)

8
24


In [18]:
#Changing specific items in array
e = np.array([[1,2,3,4,5],[2,3,4,5,6]])

In [19]:
e.shape

(2, 5)

In [24]:
#Get an element
e[0,4]

5

In [16]:
#Get row
e[0,]

array([1, 2, 3, 4, 5])

In [ ]:
e[:,0]

In [ ]:
e[1:3,1:3]

In [22]:
f=np.random.random(10,10)

TypeError: random_sample() takes at most 1 positional argument (2 given)

In [23]:
f

array([[0.94490895, 0.82446616, 0.51769843, 0.54976586, 0.80221392,
        0.50536369, 0.36656584, 0.93811029, 0.24310376, 0.40391907],
       [0.84635899, 0.33060718, 0.39578128, 0.64464443, 0.00740491,
        0.99718386, 0.23531489, 0.13500599, 0.24909823, 0.60369158],
       [0.36376582, 0.84823465, 0.36017999, 0.83121626, 0.76549653,
        0.01436609, 0.4445864 , 0.38197953, 0.25311194, 0.28209337],
       [0.81471793, 0.80372294, 0.42167382, 0.85154096, 0.65190468,
        0.21829753, 0.77016782, 0.7742751 , 0.72643212, 0.99954325],
       [0.88865047, 0.50157171, 0.34031282, 0.14215014, 0.68971118,
        0.45437694, 0.19164734, 0.37753211, 0.20126475, 0.85204502],
       [0.00380813, 0.60012878, 0.39036555, 0.28416088, 0.75347085,
        0.32532592, 0.96195386, 0.90811287, 0.87275339, 0.1533305 ],
       [0.92956236, 0.81722802, 0.79392702, 0.09457943, 0.62617561,
        0.49019163, 0.97537633, 0.23236738, 0.36973964, 0.4117204 ],
       [0.92964286, 0.35639695, 0.2704260

In [24]:
f.ndim

2

In [25]:
f.shape

(10, 10)

In [27]:
f[0:4,0:4]

array([0.94490895, 0.82446616, 0.51769843, 0.54976586])

In [26]:
f[2:5,5:7]

array([[0.01436609, 0.4445864 ],
       [0.21829753, 0.77016782],
       [0.45437694, 0.19164734]])

In [28]:
#Getting elemnts by specifying start index, end index & step
f[0,1:10:2]

array([0.82446616, 0.54976586, 0.50536369, 0.93811029, 0.40391907])

In [25]:
f = np.array([[1,2,3,4,5,6,7,8,9,10],[2,3,4,5,6,7,8,9,10,11]])

In [26]:
f[0,1:6:2]

array([2, 4, 6])

In [30]:
#Change an element
f[0,] = 10

In [31]:
f

array([[1.00000000e+01, 1.00000000e+01, 1.00000000e+01, 1.00000000e+01,
        1.00000000e+01, 1.00000000e+01, 1.00000000e+01, 1.00000000e+01,
        1.00000000e+01, 1.00000000e+01],
       [8.46358990e-01, 3.30607184e-01, 3.95781285e-01, 6.44644431e-01,
        7.40490821e-03, 9.97183864e-01, 2.35314887e-01, 1.35005988e-01,
        2.49098231e-01, 6.03691581e-01],
       [3.63765821e-01, 8.48234653e-01, 3.60179986e-01, 8.31216261e-01,
        7.65496534e-01, 1.43660923e-02, 4.44586399e-01, 3.81979532e-01,
        2.53111940e-01, 2.82093368e-01],
       [8.14717933e-01, 8.03722944e-01, 4.21673815e-01, 8.51540957e-01,
        6.51904682e-01, 2.18297525e-01, 7.70167816e-01, 7.74275099e-01,
        7.26432118e-01, 9.99543249e-01],
       [8.88650471e-01, 5.01571711e-01, 3.40312821e-01, 1.42150138e-01,
        6.89711176e-01, 4.54376937e-01, 1.91647345e-01, 3.77532114e-01,
        2.01264747e-01, 8.52045021e-01],
       [3.80812551e-03, 6.00128776e-01, 3.90365548e-01, 2.84160875e-01,
   

In [28]:
print(e)

[[10 10 10 10 10]
 [ 2  3  4  5  6]]


In [29]:
#Replace a column
e[:,2] = [99]

In [30]:
print(e)

[[10 10 99 10 10]
 [ 2  3 99  5  6]]


In [32]:
g = np.array([[[1,2,3],[4,5,6]],[[3,5,7],[5,8,9]]])

In [33]:
g

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 5, 7],
        [5, 8, 9]]])

In [34]:
g.shape

(2, 2, 3)

In [36]:
#Getting elemnts from n-d array
f = np.array([[[2,3],[3,4]],[[4,5],[5,6]]])

In [37]:
print(f)

[[[2 3]
  [3 4]]

 [[4 5]
  [5 6]]]


In [38]:
f[0,1,1]

4

In [42]:
f[0,:,1]

array([3, 4])

In [35]:
#Replacement
f[0,1,1] = 24

In [36]:
f[:,1,1]

array([24,  6])

In [43]:
f[:,1,1]= [99, 88]
f

array([[[ 2,  3],
        [ 3, 99]],

       [[ 4,  5],
        [ 5, 88]]])

In [38]:
f[:,1,:]

array([[ 3, 99],
       [ 5, 88]])

In [39]:
f[:,1,:] = [[99, 88],[55,66]]

In [40]:
f

array([[[ 2,  3],
        [99, 88]],

       [[ 4,  5],
        [55, 66]]])

In [44]:
# All 0s matrix
np.zeros((2,3,3,2),dtype='int32')

array([[[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]]]])

In [37]:
#All 1s matrix
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [38]:
#All 5s matrix
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [39]:
#Random decimal numbers
np.random.rand(4,2)

array([[0.33554331, 0.2843117 ],
       [0.81466053, 0.01044797],
       [0.02664729, 0.57130073],
       [0.45757719, 0.71828722]])

In [42]:
#Random integer numbers
np.random.randint(0,7, size=(3,3))

array([[1, 5, 0],
       [2, 2, 5],
       [6, 4, 3]])

In [43]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
#Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [53]:
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 99
output[1:4,1:4] = z 

In [54]:
print(output)

[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0. 99.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


In [56]:
#Copying arrays
a = [1,2,3]
b = a
print(b)
b[0] = 100
print(b)
print(a)

[1, 2, 3]
[100, 2, 3]
[100, 2, 3]


In [57]:
a = [1,2,3]
b = a.copy()
print(b)
b[0] = 100
print(b)
print(a)

[1, 2, 3]
[100, 2, 3]
[1, 2, 3]


In [59]:
#Elementwise arithmetic
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

print(a+b)
print(b-a)
print(a*b)
print(b/a)

[ 5  7  9 11 13]
[3 3 3 3 3]
[ 4 10 18 28 40]
[4.   2.5  2.   1.75 1.6 ]


In [60]:
print(a*23)
print(a+23)

[ 23  46  69  92 115]
[24 25 26 27 28]


In [61]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [62]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [63]:
a ** 10

array([      1,    1024,   59049, 1048576, 9765625], dtype=int32)

In [64]:
#Linear Algebra
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [65]:
print(a*b)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [14]:
a=np.array([[1,2,3],[23,24,25]])
b=np.array([[1,2],[2,3],[3,4]])
c=np.array([[1,2],[2,3]])
np.matmul(a,b)

array([[ 14,  20],
       [146, 218]])

In [67]:
#Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [68]:
#Statistics
a = np.array([[1,2],[2,3]])

In [69]:
np.min(a,axis=0)

array([1, 2])

In [70]:
np.max(a,axis=1)

array([2, 3])

In [72]:
np.sum(a, axis=0)

array([3, 5])

In [73]:
#Reorganizing arrays
a = np.array([[1,2],[2,3]])
print(a.shape)

(2, 2)


In [75]:
b = a.reshape((4,1))
print(b)

[[1]
 [2]
 [2]
 [3]]


In [78]:
#Vertically stacking vectors
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

np.vstack([a,b,b,a])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [81]:
#Horizantally stacking vectors
a = np.ones((2,4))
b = np.zeros((2,2))

np.hstack([a,b])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [85]:
#Load data from file
my_data = np.genfromtxt('data.txt', delimiter = ',')
my_data.astype('int32')

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
#Boolean Masking and Advanced Indexing
my_data > 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [87]:
my_data[my_data > 5]

array([6., 7., 8., 9.])

In [88]:
#Index list in NumPY
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[[1,5,7]]

array([2, 6, 8])

In [89]:
((a > 5) & (a > 2))

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [1]:
import numpy as np
## Linear Algebra
## x + 2y = 10
## 3x + 5y = 25
a = np.array([[1,2],[3,5]])
b = np.array([10,25])

x = np.linalg.solve(a,b)

x

array([0., 5.])

In [ ]:
#x + 2y + 24z = 189
#3x + 4y + z = 215
#4x + 4y+ 8z = 240

In [ ]:
x[0]*a[0,0]+x[1]*a[0,1]+x[2]*a[0,2]

In [2]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])